apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: generic-clusterwide-alert-rules
  labels:
    release: kube-prometheus-stack
spec:
  groups:
  - name: generic-clusterwide-alerts-rules
    rules:
      # 1. Pod is stuck in a failing state (CrashLoop, ImagePull, etc)
      - alert: PodStuckInWaitingState
        expr: |
          sum by (namespace, pod, reason) (
            kube_pod_container_status_waiting_reason{
              namespace="csauditor", 
              reason=~"CrashLoopBackOff|ImagePullBackOff|CreateContainerConfigError"
            }
          ) > 0
        for: 1m
        labels:
          severity: critical
          team: devops
        annotations:
          summary: "Pod {{ "{{" }} $labels.pod {{ "}}" }} is stuck in {{ "{{" }} $labels.reason {{ "}}" }}"
          description: "Pod {{ "{{" }} $labels.pod {{ "}}" }} in namespace {{ "{{" }} $labels.namespace {{ "}}" }} has been in {{ "{{" }} $labels.reason {{ "}}" }} for more than 5m."

      # 2. Any Deployment in csauditor is completely down
      - alert: DeploymentAtZeroReplicas
        expr: kube_deployment_status_replicas_available{namespace="csauditor"} == 0
        for: 2m
        labels:
          severity: critical
          team: devops
        annotations:
          summary: "Deployment {{ "{{" }} $labels.deployment {{ "}}" }} is DOWN"
          description: "The deployment '{{ "{{" }} $labels.deployment {{ "}}" }}' in namespace '{{ "{{" }} $labels.namespace {{ "}}" }}' has 0 available replicas. This service is currently unreachable."

      # 3. High Memory Utilization (> 90%)
      - alert: ContainerHighMemoryUsage
        expr: |
          (
            sum by (namespace, pod, container) (container_memory_working_set_bytes{container!="", container!="POD"}) 
            / on (namespace, pod, container) 
            kube_pod_container_resource_limits{resource="memory"}
          ) * 100 > 90
        for: 5m
        labels:
          severity: warning
          team: devops
        annotations:
          summary: "High Memory usage on {{ "{{" }} $labels.pod {{ "}}" }} namespace {{ "{{" }} $labels.namespace {{ "}}" }}"
          description: "Container {{ "{{" }} $labels.container {{ "}}" }} is using {{ "{{" }} $value | printf \"%.2f\" {{ "}}" }}% of its memory limit."

      # 4. High CPU Utilization (> 90%)
      - alert: ContainerHighCPUUsage
        expr: |
          (
            sum by (namespace, container, pod) (rate(container_cpu_usage_seconds_total{container!="", container!="POD"}[5m])) 
            / on (namespace, pod, container) 
            kube_pod_container_resource_limits{resource="cpu"}
          ) * 100 > 90
        for: 5m
        labels:
          severity: warning
          team: devops
        annotations:
          summary: "High CPU usage on {{ "{{" }} $labels.pod {{ "}}" }} namespace {{ "{{" }} $labels.namespace {{ "}}" }}"
          description: "Container {{ "{{" }} $labels.container {{ "}}" }} is using {{ "{{" }} $value | printf \"%.2f\" {{ "}}" }}% of its CPU limit."
        
      # 5. Node Memory Usage (> 80%)
      - alert: NodeHighMemoryUsage
        expr: |
          (
            1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)
          ) * 100 > 80
        for: 5m
        labels:
          severity: warning
          team: devops
        annotations:
          summary: "Node {{ "{{" }} $labels.instance {{ "}}" }} High Memory Usage"
          description: "Node {{ "{{" }} $labels.instance {{ "}}" }} memory usage is at {{ "{{" }} $value | printf \"%.2f\" {{ "}}" }}%. Cluster performance may degrade."

      # 6. Disk Volume Usage (> 80%)
      - alert: NodeHighDiskUsage
        expr: |
          (
            1 - (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"})
          ) * 100 > 60
        for: 5m
        labels:
          severity: critical
          team: devops
        annotations:
          summary: "Node {{ "{{" }} $labels.instance {{ "}}" }} High Disk Usage"
          description: "Root partition on node {{ "{{" }} $labels.instance {{ "}}" }} is {{ "{{" }} $value | printf \"%.2f\" {{ "}}" }}% full. Clean up logs or expand volume."

      # 7. Persistent Volume (PV) Usage (> 80%)
      - alert: PersistentVolumeUsageHigh
        expr: |
          (
            kubelet_volume_stats_used_bytes 
            / 
            kubelet_volume_stats_capacity_bytes
          ) * 100 > 60
        for: 5m
        labels:
          severity: critical
          team: devops
        annotations:
          summary: "Persistent Volume {{ "{{" }} $labels.persistentvolumeclaim {{ "}}" }} High Usage"
          description: "PVC {{ "{{" }} $labels.persistentvolumeclaim {{ "}}" }} in namespace {{ "{{" }} $labels.namespace {{ "}}" }} is {{ "{{" }} $value | printf \"%.2f\" {{ "}}" }}% full."
