appRepo: https://github.com/rbalman/otel-k8s-config.git
revision: HEAD
addonsPath: dev/addons

apps:
  ingress:
    enabled: true
    syncWave: "1"
    namespace: ingress-nginx

  minio:
    enabled: true
    syncWave: "1"
    namespace: minio

  prometheus:
    enabled: true
    syncWave: "2"
    namespace: monitoring

  grafana:
    enabled: true
    syncWave: "2"
    namespace: monitoring

  loki:
    enabled: true
    syncWave: "3"
    namespace: loki

  jaeger:
    enabled: true
    syncWave: "3"
    namespace: monitoring

  otel-cluster:
    enabled: true
    syncWave: "4"
    namespace: monitoring

  otel-node:
    enabled: true
    syncWave: "4"
    namespace: monitoring
