valuesRepo: https://github.com/rbalman/temp-repo.git
valuesRevision: HEAD
addonsPath: dev/addons

apps:
  minio:
    syncWave: "1"
    namespace: minio
    chartRepo: https://charts.min.io/
    chart: minio
    version: 5.4.0

  prom-stack:
    syncWave: "2"
    namespace: monitoring
    chartRepo: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    version: 84.0.1
    extraSyncOptions:
      - ServerSideApply=true

  loki:
    syncWave: "3"
    namespace: loki
    chartRepo: https://grafana.github.io/helm-charts
    chart: loki
    version: 7.0.0

  alloy:
    syncWave: "4"
    namespace: loki
    chartRepo: https://grafana.github.io/helm-charts
    chart: alloy
    version: 0.12.5

  jaeger:
    syncWave: "3"
    namespace: monitoring
    chartRepo: https://jaegertracing.github.io/helm-charts
    chart: jaeger
    version: 4.8.0

  otel-collector:
    syncWave: "4"
    namespace: monitoring
    chartRepo: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    version: 0.116.0
