{{- range $name, $app := .Values.apps }}
{{- if ne $app.enabled false }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $name }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: {{ $app.syncWave | quote }}
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  source:
    repoURL: {{ $.Values.appRepo }}
    targetRevision: {{ $.Values.revision }}
    path: {{ $.Values.addonsPath }}/{{ $name }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $app.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      {{- range $app.extraSyncOptions }}
      - {{ . }}
      {{- end }}
{{- end }}
{{- end }}
