{{- range $name, $app := .Values.apps }}
{{- if ne $app.enabled false }}
{{- $valuesPath := $app.valuesPath | default (printf "%s/%s/values.yaml" $.Values.addonsPath $name) }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $name }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: {{ $app.syncWave | quote }}
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  sources:
    - repoURL: {{ $app.repoURL }}
      chart: {{ $app.chart }}
      targetRevision: {{ $app.targetRevision }}
      helm:
        valueFiles:
          - $values/{{ $valuesPath }}
    - repoURL: {{ $.Values.repoURL }}
      targetRevision: {{ $.Values.targetRevision }}
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $app.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      {{- range $app.extraSyncOptions }}
      - {{ . }}
      {{- end }}
{{- end }}
{{- end }}
