mode: standalone
persistence:
  size: 10Gi
resources:
  requests:
    memory: 1Gi
rootUser: "minioadmin"
rootPassword: "minioadmin"
service:
  type: ClusterIP

buckets:
  - name: loki
    policy: none
    purge: false
  - name: thanos
    policy: none
    purge: false

users:
  - accessKey: loki
    secretKey: loki-secret
    policy: readwrite