valuesRepo: https://github.com/rbalman/temp-repo.git
valuesRevision: HEAD
appsPath: dev/apps

apps:
  otel-app:
    namespace: default
    chartRepo: https://rbalman.github.io/otel-app
    chart: otel-app-chart
    version: 0.1.0
